# #This chart compares 5 different countries across the globe, and shows how they rank in terms of death count
# from unsafe drinking water sources. Each country has different economical systems and policies that 
# dictate the way water systems and sanitiation is executed and accessible. 
# From the chart we are able to see that countries such as Africa, have a high number of deaths
# in comparison to the US or UK, which is caused by multiple factors such as economical stability
# and infrastructure barriers that make it harder for water sanitation and systems to be implemented there. 

file <- "C:/Users/diyak/OneDrive/Documents/info201/assignments/project-danielz6/data/death-rates-unsafe-water.csv"

death_data <- read.csv(file)

total_deaths_by_country <- death_data %>%
  group_by(Entity) %>%
  summarise( Deaths...Cause..All.causes...Risk..Unsafe.water.source...Sex..Both...Age..Age.standardized..Rate. = sum(Deaths...Cause..All.causes...Risk..Unsafe.water.source...Sex..Both...Age..Age.standardized..Rate.)) %>%
  #  filter(grepl('Afghanistan|Africa|United States|Unites Kingdom|Mexico', Entity, fixed = TRUE))  
  filter(Entity %in% c("Afghanistan","African Region (WHO)","United States","United Kingdom","Mexico"))

view(total_deaths_by_country)
barplot(total_deaths_by_country$Deaths...Cause..All.causes...Risk..Unsafe.water.source...Sex..Both...Age..Age.standardized..Rate.,
        names=c("Afghanistan","African Region (WHO)","United States","Unites Kingdom","Mexico"),
        las = 2,
        ylab = "Total Deaths By Country",
        main = "Cumulative sum of deaths by death betwen 1990 - 2019")


# The global access to drinking water are visualized in this data table. There are different levels of standards for their 
# facilities; Safely Managed, Basic, Limited, Unimproved, and No access (Surface Water Only).
# Shown in the columns are the percentage of the globe's data on their access to a drinking water facility. 
# This data table is important in visualizing the most current year (2020) of
# the data set of global access to drinking water facilities.

library(dplyr)
library(tidyverse)
data <- "C:/Users/eddyw/Documents/Info 201/project-danielz6/data/access-drinking-water-stacked.csv"
wateraccessdata <- read.csv(data)

USA_2020 <- wateraccessdata %>%
  drop_na() %>%
  group_by(Code) %>%
  filter(Code == "USA") %>% 
  filter(Year == 2020) %>%
  summarise(Safely_Managed = sum(wat_sm), Basic = sum(wat_bas_minus_sm), Limited = sum(wat_lim), Unimproved = sum(wat_unimp), No_Access = sum(wat_sur))

UGA_2020 <- wateraccessdata %>%
  drop_na() %>%
  group_by(Code) %>%
  filter(Code == "UGA") %>% 
  filter(Year == 2020) %>%
  summarise(Safely_Managed = sum(wat_sm), Basic = sum(wat_bas_minus_sm), Limited = sum(wat_lim), Unimproved = sum(wat_unimp), No_Access = sum(wat_sur))

NZL_2020 <- wateraccessdata %>%
  drop_na() %>%
  group_by(Code) %>%
  filter(Code == "NZL") %>% 
  filter(Year == 2020) %>%
  summarise(Safely_Managed = sum(wat_sm), Basic = sum(wat_bas_minus_sm), Limited = sum(wat_lim), Unimproved = sum(wat_unimp), No_Access = sum(wat_sur))

MEX_2020 <- wateraccessdata %>%
  drop_na() %>%
  group_by(Code) %>%
  filter(Code == "MEX") %>% 
  filter(Year == 2020) %>%
  summarise(Safely_Managed = sum(wat_sm), Basic = sum(wat_bas_minus_sm), Limited = sum(wat_lim), Unimproved = sum(wat_unimp), No_Access = sum(wat_sur))

CAN_2020 <- wateraccessdata %>%
  drop_na() %>%
  group_by(Code) %>%
  filter(Code == "CAN") %>% 
  filter(Year == 2020) %>%
  summarise(Safely_Managed = sum(wat_sm), Basic = sum(wat_bas_minus_sm), Limited = sum(wat_lim), Unimproved = sum(wat_unimp), No_Access = sum(wat_sur))

GBR_2020 <- wateraccessdata %>%
  drop_na() %>%
  group_by(Code) %>%
  filter(Code == "GBR") %>% 
  filter(Year == 2020) %>%
  summarise(Safely_Managed = sum(wat_sm), Basic = sum(wat_bas_minus_sm), Limited = sum(wat_lim), Unimproved = sum(wat_unimp), No_Access = sum(wat_sur))

PRK_2020 <- wateraccessdata %>%
  drop_na() %>%
  group_by(Code) %>%
  filter(Code == "PRK") %>% 
  filter(Year == 2020) %>%
  summarise(Safely_Managed = sum(wat_sm), Basic = sum(wat_bas_minus_sm), Limited = sum(wat_lim), Unimproved = sum(wat_unimp), No_Access = sum(wat_sur))

data_table_2020 <- rbind(NZL_2020, GBR_2020, CAN_2020, USA_2020, PRK_2020, MEX_2020, UGA_2020)

colnames(data_table_2020)[1] <- "Country"

knitr::kable(head(data_table_2020[, 1:5]), "pipe")

view(data_table_2020)



# This chart compares the trend in deaths from unsafe drinking water in the United States and Australia, 
# starting from the year 200. In viewing the trend in data, we are able to see the change in deaths 
# for each country, and we can observe that the United States has seen a large decline in the death rate
# from 2000-2020, whereas Australia has seen a steep increase. Comparatively, these two countries 
# have a similar economic standing and similar infrastructure in the way that water systems and sanitation is 
#implemented. This leads to us knowing that there are other factors that are an influence to access
# to safe water, even with countries that would be categorized as similar.

library(tidyverse)
file <- "C:/Users/diyak/OneDrive/Documents/info201/assignments/project-danielz6/data/death-rates-unsafe-water.csv"
death_data <- read.csv(file)

usa <- death_data %>%
  filter(Entity == "United States") %>%
  filter(as.numeric(Year) > 1999) %>%
  select (3,4)

#view(usa)

aus <- death_data %>%
  filter(Entity == "Australia")  %>%
  filter(as.numeric(Year) > 1999) %>%
  select (3,4)

#view(aus)

plot(usa$Year, usa$Deaths...Cause..All.causes...Risk..Unsafe.water.source...Sex..Both...Age..Age.standardized..Rate.,type = "o",col = "red", xlab = "Years", ylab = "Death Rate", 
     main = "Death Rate Trends [2000 - 2019]",
     ylim=c(0.02,0.15))

lines(aus$Year, aus$Deaths...Cause..All.causes...Risk..Unsafe.water.source...Sex..Both...Age..Age.standardized..Rate., type = "o", col = "blue")

#legend(x=topright,y=0.92, legend=c("Equation 1", "Equation 2"), fill = c("blue","red"))
legend( x= "topleft", y=0.92,
        legend=c("Australia","United States"),
        col=c("blue", "red"),
        pch=c("-","-", "-", "-"))
        
        
        file <- "C:/Users/diyak/OneDrive/Documents/info201/assignments/project-danielz6/data/death-rates-unsafe-water.csv"

death_data <- read.csv(file)

uk <- death_data %>%
  filter(Entity == "United States") %>%
  select (1,4)

usa <- death_data %>%
  filter(Entity == "United Kingdom") %>%
  select (1,4)

boxplot(uk$Deaths...Cause..All.causes...Risk..Unsafe.water.source...Sex..Both...Age..Age.standardized..Rate.,
        usa$Deaths...Cause..All.causes...Risk..Unsafe.water.source...Sex..Both...Age..Age.standardized..Rate., 
        ylim = range(0.01:2),
        ylab = "Death Range",
        names=c("US", "UK"))
        title(main = "Death Rates from Unsafe Water Sources")
        
# #This chart displays the comparison of death rates between the US, and the UK, that are both considered to be ranked 
# highly in terms of socioeconomical standing. This chart shows the range of death rates, which we can observe to be fairly 
 # low in these two countries.
# From that, we can see that countries that are considered wealthier, and are 
 #economically stronger appear to have lower death rate ranges. 
# By comparing two countries that have a similar death range and are at a 
  #similar global economic standing, we are able to conclude that 
  #countries having a higher socioeconomical standing tend to have better water systems and sanitation. 
#This is  resulting in a lower range of deaths from unsafe drinking water. 


# Example: Project Data Access Functions  ----
#----------------------------------------------------------------------------#
# These functions are used to access data sources ... 
#----------------------------------------------------------------------------#
data_access_test <- function (name="World!") {
  t <- paste0("Hello: ", name)
  return(t)
}
