
| **Drinking water access (Global)**  | **\Global Percentage (2020)** |**\Global Percentage (2015)**|**\Global Percentage (2010)**|**\Global Percentage (2005)**|**\Global Percentage (2000)**|
|-------------------------------------|------------------------------|----------------------------|----------------------------|----------------------------|----------------------------|
| Safely Managed                      | 74.27%                       | 70.2%                      | 65.76%                     | 63.4%                      | 61.73%                     |
|-------------------------------------|------------------------------|----------------------------|----------------------------|----------------------------|----------------------------|
| Basic                               | 15.84%                       | 18.02%                     | 20.44%                     | 20.54%                     | 19.96%                     |
|-------------------------------------|------------------------------|----------------------------|----------------------------|----------------------------|----------------------------|
| Limited                             | 3.62%                        | 3.37%                      | 3.05%                      | 2.76%                      | 2.50%                      |
|-------------------------------------|------------------------------|----------------------------|----------------------------|----------------------------|----------------------------|
| Unimproved                          | 4.71%                        | 6.25%                      | 7.94%                      | 9.79%                      | 11.76%                     |
|-------------------------------------|------------------------------|----------------------------|----------------------------|----------------------------|----------------------------|
| No access (Surface Water only)      | 1.56%                        | 2.16%                      | 2.81%                      | 3.52%                      | 4.05%                      |

## Access to drinking water data table

The global access to drinking water are visualized in this data table. There are different levels of standards for their facilities; Safely Managed, Basic, Limited, Unimproved, and No access (Surface Water Only). Shown in the columns are the percentage of the globe's data on their access to a drinking water facility. Starting from 2020 back to 2000, data is presented in five-year intervals. This data table is important in visualizing the improvement of global access to drinking water facilities over the past ~two decades.